# Generated by Django 5.1.3 on 2024-11-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.user')),
            ],
        ),
    ]
