# Generated by Django 5.1.3 on 2024-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0005_reviewfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
